package org.example.items;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;

/**
 * This is a subclass that describes a book it has a genre, which is a enum, and USBN is a unique string inherent to each
 * book object and it is generated by its hashcode
 * Responsable is externally called author
 */
@EqualsAndHashCode(callSuper = true)
public class Book extends Item {
    @Getter @Setter
    private Genre genre;
    @Getter
    private String USBN;

    public Book(String title, String author, Genre genre) {
        super(title, author);
        this.genre = genre;
        super.type = Type.BOOK;

        USBN = String.format("%d", hashCode());
    }

    @Override
    public void setTitle(String title) {
        super.setTitle(title);
        USBN = String.format("%d", hashCode());
    }

    public void setAuthor(String author) {
        super.setResponsable(author);
        USBN = String.format("%d", hashCode());
    }

    public String getAuthor() {
        return super.getResponsable();
    }

    @Override
    public String toString() {
        return String.format("Book {\n" +
                        super.toString() +
                        "Author: %s\n" +
                        "USBN: %s\n"+
                        "} \n",
                this.getAuthor(), USBN);
    }

    public enum Genre {
        MYSTERY, ROMANCE, FANTASY, SCIFI, HORROR, BIOGRAPHY, HISTORY, SCIENCE, LANGUAGE, PHILOSOPHY
    }
}
